### PR TITLE
Avoid button tap inside DMs

### PR DESCRIPTION
**Pull request by akshaykhanapuri**
1) Changed the parameter being passed to the function `findByClassName` from `artdeco-button--secondary` to` artdeco-button--secondary invitation-card__action-btn`
2) Added .env to gitignore

### CODE REVIEW

**Comment by hkirat** [comment]
This looks right, will test it out and merge it in if it works!

**Comment by hkirat** [comment]
Thanks for adding dotenv as well?

**Comment by hkirat** [comment]
Please post your SOL wallet address here!

**Comment by akshaykhanapuri** [comment]
Thank you for the merge @hkirat. This was my first contribution to an open source project. So I have already gained a lot of value from this. Thank you for the amazing content that you create.
Godspeed!

**Pull request merged**
