### PR TITLE
Feature/adding read me file

### PR DESCRIPTION
**Pull request by saiprakash2**

### CODE REVIEW

**Review by raghu-007 — COMMENTED** [review]
we need a elaborated readme file😀

**Comment by saiprakash2** [comment]
I created it for fun just to increase my commits.😂😂

You can create your pull request, I will close this.

**Comment by x0samnan** [comment]
@saiprakash2 Please, close this PR. I think #6 is more than complete for now and this PR won't be required.

**Comment by saiprakash2** [comment]
Sure.

**Pull request closed without merging**
